---

- block:
  - name: using shell
    shell: echo $SHELL
    register: used_shell
    changed_when: False
    check_mode: no

  - block:
    - name: get /etc/shells list
      shell: cat /etc/shells
      register: shells_lists
      changed_when: False
      check_mode: no

    - block:
      - name: add zsh path to /etc/shells
        shell: echo /usr/local/bin/zsh >> /etc/shells
        become: True
        when: '"/usr/local/bin/zsh" not in shells_lists.stdout_lines'

      - name: change the login shell
        shell: chsh -s /usr/local/bin/zsh
        become: True

    when: '"/usr/local/bin/zsh" not in used_shell'

  tags:
    - chsh
