---

- block:
  - name: get file list in the $HOME derectory list
    shell: echo &HOME/*
    register: HOME_list
    changed_when: False
    check_mode: no

  - block:
    - name: clone dofiles repository
      git:
        repo: https://github.com/faluna/dotfiles.git
        dest: ~/dotfiles
        depth: 1
      when: '"dotfiles" not in HOME_list.stdout'
  - tag:
    - dotfiles
