---

- blocks:
  - name: make directory "colors"
    file:
      path: ~/colors
      state: directory
      mode: 0755

  - name: get Iceberg for terminal
    get_url:
      url: https://github.com/aseom/dotfiles/blob/master/osx/iterm2/iceberg.itermcolors
      dest: ~/color/iceberg.itermcolors

