---

- block:

  - name: already tapped
    shell: brew tap
    register: brew_taps_list
    changed_when: False
    check_mode: no

  - block:

    - name: homebrew tap
      homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: 
        - "{{ taps }}"
        
        
    - block:
      
        - name: install fonts by brew cask
          environment:
            HOMEBREW_CASK_OPTS: --appdir=/Applications
          homebrew_cask:
            name: "{{ item.name }}"
            state: "{{ item.state | default('present') }}"
          with_items: "{{ packages }}"

        - name: install xquartz
          homebrew_cask:
            name: xquartz
            state: present
        - name: install ricty
          homebrew:
            name: ricty
            state: present
        # - name: install ricty with powerline
          # homebrew:
            # name: ricty
            # state: present
            # install_options: with-powerline
        - name: copy generated font file
          shell: "cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/"
          args:
            creates: ~/Library/Fonts/Ricty-Bold.ttf
          notify: run fc-cache
        - name: make directory fonts
          file:
            path: $HOME/fonts
            state: directory
        - name: clone fontmerger
          git:
            repo: https://github.com/iij/fontmerger
            dest: $HOME/fonts/fontmerger
            depth: 1
        - name: create Ricty Discord patched all icons 
          shell: bin/fontmerger --all -o ~/Library/Fonts/ --suffix=with-all-icons -- ~/Library/Fonts/RictyDiscord-Regular.ttf
          args:
            chdir: $HOME/fonts/fontmerger/
          notify: run fc-cache
      tags:
        - cask_fonts
  tags:
    - fonts
